### ISSUE TITLE
Change default keybinding to eg. string selection

### ISSUE THREAD

**Issue by tukoz** [conformal/xombrero#113]
How to re-bind keybinding so that:
`C-Left` & `C-Right` (or vim-like `b` & `w`) -» go back & forth a word, just like it does in the command line.
`C-S-Left` & `C-S-Right` to select some string
C-z -» undo last action in any fiefld, eg. undo the last paste or typed strings.

Added these to ~/.conformal.conf

    keybinding = tabnext,!C-Tab
    keybinding = tabprevious,!S-C-Tab
But couldn't even change `C-←/→` default to shift tabs back and forth :/ :+1:  
 
Started digging my way through Xombrero, I like many things (eg size(!), diy conf, browser modes, some vim-like keybindings) but I find myself on another tab having to revert to mouse or touchpad each time my fingers pressed C-←/→ or C-S-←/→. Happens a lot and breaks my workflow, making xombrero usable for reading only.

Xombrero: 1.6.4 - WebKit: 2.4.9 - WebKit API: 3,0
I used #56

**Comment by musicsmithnz** [comment]
Hey dude!!! 
My thinking is very similary to you! I really want the standard browser AND the standard vim commands to be available. For example: 
Browser Standard
tabnext=ctl-tab
tabprevious= ctl-shift-tab

but the standard xombrero config changes this to:

tabnext=ctl-right
tabprevious=ctl-left

Why?!!!!

also I frequently use 'ctl-left' 'ctl-right' in order to edit my input into fields such as search fields(move back and forth one word), forms or comments. but this is used for tabs! It disturbs my workflow so much!!!
I really want to use xombrero, but i can't figure out how to change these defaults. I made the $HOME/.xombrero.conf file(why is the default not $HOME/.xombrero/.xombrero.conf!! this way there are two files in the HOME instead of one!!).

This is my $HOME/.xombrero.conf file

keybinding = tabprevious,!S-C-Tab
keybinding = tabnext,!C-Tab

for some reason tabnext IS working, but not tabprevious. Do you have any idea how to fix these issues:

1) instead of ctl-left ctl-right changing tabs:
a) Ctl-Left/Right key moves word by word within the field in focus
b) Ctl-Shift-Left/Right key selects word by word within the field in focus

2) tabprevious is triggered by Ctl-Shift-Tab

I have been using these commands for years on other browsers, although xombrero fixes some things, it has destroyed these defaults!
These changes are also unjustified, as in vim ctl-left/right behaves the same as in a browser, ie. it moves back and forward a word, not changes tab!!!

Please help me if you can !!! I love the idea of a vim like browser... but some feautures are not like vim AND not like any browser that I know of.

**Comment by musicsmithnz** [comment]
if i can find a way to change this i might fork it and add my own standard configs and profiles to make this easier for anyone to edit.

I want to make a distribution in the future designed for power users and maximum customization/configurability. xombrero will most likely be my recommonded browser, but the present configuration is not helpful.
the man file says not to use shift because it gets in the way of non US keyboards. But i type in Chinese sometimes using fcitx and use Ctl-Shft-1,Ctl-Shft-2 etc to change languages, in China the standrd(for Sogu) is Ctl-Shift, still no issue. I can't see how this is an issue.

editing this post is so frustrating, everytime i want to delete a word by using Ctl-Shift-Left I end up changing tabs !!

**Comment by tukoz** [comment]
Hey, I found it! Reading the man page:
> Actions may be any xombrero command that can be run from the command prompt.
> With one additional action, 'unbind' which will unbind any previous actions
> to that keybinding.

So in the conf:

    # keybinding    = tabprevious,!C-Left
    keybinding      = unbind,!C-Left
    keybinding      = tabprevious,!C-Page_Up
    keybinding      = tabprevious,!C-S-Tab        # that one doesn't work
    # keybinding    = tabnext,!C-Right
    keybinding    = unbind,!C-Right
    keybinding    = tabnext,C-Page_Down
    keybinding    = tabnext,C-Tab

Enjoy!
