### ISSUE TITLE
[osx] maximum webkitgtk version?

### ISSUE THREAD

**Issue by dunn** [conformal/xombrero#119]
I've been looking into making a Homebrew formula for xombrero, and I've run into some difficulties.  The version of WebKitGTK+ in Homebrew is 2.10.4, so in [the Makefile](https://github.com/conformal/xombrero/blob/master/osx/Makefile#L8) I had to replace "webkitgtk-3.0" with "webkit2gtk-4.0" and in [`xombrero.h`](https://github.com/conformal/xombrero/blob/master/xombrero.h#L103), "\<webkit/webkit.h\>" with "\<webkit2/webkit2.h\>".  But the build fails with WebKit-related errors: https://gist.github.com/anonymous/9f57af3e308db714f3f2#file-01-make-L19

Is xombrero only compatible with WebKitGTK+ 1.x.x?

**Comment by dunn** [comment]
Oops; this is xombrero 1.6.4.

**Comment by marcopeereboom** [comment]
Unfortunately, yes.

We briefly looked at the 2.x stuff but that would basically be a rewrite and even more unfortunate is that not all required hooks to make a “secure” browser are available.

This information is dated though and maybe good things have happened since.  I may look at this in the future.

**Comment by dunn** [comment]
Got it, thank you!  Feel free to close, unless you want to treat this as a tracking issue.
