### ISSUE TITLE
Segfault while browsing most sites

### ISSUE THREAD

**Issue by aplainzetakind** [conformal/xombrero#129]
I'm on Debian Jessie.

`[19042.952921] xombrero[21222]: segfault at 0 ip 00007f1e218d9e20 sp 00007fffa1c574e8 error 4 in libjavascriptcoregtk-3.0.so.0.16.17[7f1e21417000+6c8000]`

**Comment by tukoz** [comment]
Using Xombrero as the main browser here on my tiny laptop / Archlinux and no segfault so far. You use the binary or compiled it?

**Comment by aplainzetakind** [comment]
I installed it from the Debian repos.

**Comment by marcopeereboom** [comment]
webkit issue.  We don’t control that.

**Comment by dradux** [comment]
I have the same issue as @aplainzetakind, I'm running debian sid, installed from the repos. It sounds right that this is a webkit issue as I've verified the crash with other webkit based browsers (surf).

While it may be a webkit issue, does this mean xombrero cannot do anything? I've had this issue for several months and it is getting to the point that I cannot trust xombrero for daily use. Is there a library and/or version of webkit we can downgrade to? Any info on what the issue is?

More Detail on this issue:
It is not 100% reproducable but going to this wunderground link: https://www.wunderground.com/cgi-bin/findweather/getForecast?query=natick,%20ma seems to cause a crash every time. Just open the page and usually after 10-15 seconds I get a segfault, sometimes it take up to a minute.

**Comment by tukoz** [comment]
webkitgtk{2} 2.4.10 here. wunderground works fine whether without or with JS (animated maps incl.)

Btw does it crash too while in whilelist and without JS?

**Comment by dradux** [comment]
I was in whitelist mode but with js enabled. 

If I disable JS it does not appear to crash (I left it for over 5 minutes) however the 10-day weather forecast and map section does not render and my hunch is something one of the two is causing the crash. If I enable JS on the page it crashed in roughly 45 seconds after page load complete.

My xombrero About info
Version: 1.6.4
WebKit: 2.4.9
User Agent: 538.15
WebKit API: 3.0

**Comment by dradux** [comment]
I've looked into this more, other webkit based browsers (surf, luakit) also segfault; however midori did not. I downgraded webkit to 2.4.9-1~deb8u1 and reinstalled xombrero from the apt repo and the issue appears to be resolved. I will test more and if the issue is resolved post more details on how I had to downgrade packages.

**Comment by marcopeereboom** [comment]
webkit issues.  Have your upstream package maintainer update to a working version.
