### ISSUE TITLE
WebKit2

### ISSUE THREAD

**Issue by vap3r** [conformal/xombrero#142]
xombrero has been great for the past few years, but are there plans to move to WebKit2?

**Comment by keenerd** [comment]
It came up in 2015 and doesn't sound like there are any plans: https://github.com/conformal/xombrero/issues/119#issuecomment-163031674

I've been taking a look at the Epiphany patches from when they migrated to webkit2 and seeing what I could apply.  To me it feels like a three-way split between simple name cleanup, some structure shuffling and then more complicated stuff I still don't understand.  There are some non-trivial ifdefs in there.

Xombrero will probably be removed from Arch's repos as part of all webkit1 software, because of the open CVEs.

**Comment by marcopeereboom** [comment]
I don't have plans to do a webkit2 release.  If someone feels inclined I am willing to help but I won't have time to do the heavy lifting.
