### ISSUE TITLE
Very disappointed to find no window position option in .xombrero.conf

### ISSUE THREAD

**Issue by rickan54** [conformal/xombrero#152]
I really think that issue #14, "Option to save window size/placement" was not handled well at all considering that xombrero is supposed to be usable without a mouse.  It most definitely does NOT NEED to be done by the window manager. If it's going to happen reliably then the application needs to handle it.

I see that the size can at least be set in the .xombrero.conf file, and I was VERY disappointed to find that the window position (i.e. placement) was not included. (Is this lack of thoroughness pervasive in xombrero?)

This is my second issue, and the first one killed my enthusiasm for xombero. (Actually I discovered the issues in the opposite order to the order I posted them, so it might be cumulative.)

My initial enthusiasm was very high because I started using vi in 1979 (and ed prior to that) and it (vim, really) is still my preferred editor. It's been way too many times I've typed vi commands into my browser!

**Comment by jrick** [comment]
It can't be done reliably by the application because the window manager can always override what the application tries to do with its own window.  The only thing the application has complete control over is how it renders stuff inside its own window.

And as a former xombrero dev let me say this: you should not be using xombrero in 2017, especially if you are looking for any kind of a secure web browser.  There is no secure webkitgtk release that xombrero is capable of using.  I won't bore you with the details in this reply but please see https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/ for a full explanation of the issues.
