### ISSUE TITLE
xombrero changing permissions of download_dir on launch

### ISSUE THREAD

**Issue by sysfu** [conformal/xombrero#35]
For some reason xombrero is changing the permissions of the download_dir folder from the default 755 to 700 on application launch.

Is this necessary to the proper operation of the application? If not, I would like to see this behavior eliminated please.

**Comment by marcopeereboom** [comment]
I am not reconsidering this.

**Comment by Neqoxec** [comment]
This issue is detrimental to those running software under multiple users, offers no security benefit to anyone with a basic understanding of file permissions, and is easily fixed. Checking the permissions of the download directory is not xombrero's job or concern.

Going to leave a patch here for those who stumble across this issue in the future, don't mind applying an out-of-band fix:

```
diff --git a/xombrero.c b/xombrero.c
index 35d3911..3c9b185 100644
--- a/xombrero.c
+++ b/xombrero.c
@@ -8413,13 +8413,6 @@ xxx_dir(char *dir)
        }
        if (S_ISDIR(sb.st_mode) == 0)
                errx(1, "%s not a dir", dir);
-#if !defined __MINGW32__
-       if (((sb.st_mode & (S_IRWXU | S_IRWXG | S_IRWXO))) != S_IRWXU) {
-               warnx("fixing invalid permissions on %s", dir);
-               if (chmod(dir, S_IRWXU) == -1)
-                       err(1, "chmod %s", dir);
-       }
-#endif
 }
 
 void
```

**Comment by marcopeereboom** [comment]
I strongly disagree.

I can not fathom shared use of a browser that is not an extremely bad idea.

**Comment by witeshadow** [comment]
I agree with both views. What would satisfy each side though? User profiles? Encouraging this browser to use its own dl dir and not a common one? Notifying users of the permission change regardless of how the browser is opened?
